### PR TITLE
fix failing test suite

### PR DESCRIPTION
**Pull request by marco-jantke**
It seems it was forgotten to update the test suite after this commit
51cf0bfc9a579250746db94befa282c697a983a6.

### CODE REVIEW

**Comment by marco-jantke** [comment]
The suite for PHP 5.3.3. fails because of PHP >= 5.3.9 dependency of the symfony/console lib. Is it ok for you to remove this from the .travis.yml?

**Comment by marco-jantke** [comment]
Ping.

**Comment by marco-jantke** [comment]
Ping.

**Comment by aboks** [comment]
This PR is the same as #119, which is already open for more than 6 months.

@sebastianbergmann what are your plans regarding phpcpd? Do you plan to keep maintaining and developing it? Otherwise maybe it would be best to mark the project as abandoned and/or allow someone else to take over maintenance.

**Comment by sebastianbergmann** [comment]
Merged #119.

**Pull request closed without merging**
