### PR TITLE
Support Symfony 2.7 LTS

### PR DESCRIPTION
**Pull request by sergeyz**
Great to use https://github.com/sebastianbergmann/phpcpd/pull/100 together with Symfony 2.7-2.8

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I am hesitant to add support for an old dependency.

Simply use this tool from a PHAR instead of installing it via Composer and you're all set.

**Comment by sergeyz** [comment]
We have a lot of tools and share them with our community. Orchestrating PHARs on CI servers and in private\public repositories is too complex in our case, that's why we use require-dev, to track dependencies in a single place. Symfony 2.7 is active release for a year https://symfony.com/roadmap?version=2.7#checker so would be good to see its support, considering that support costs nothing in this specific case. I commit to supporting any issue happens with Symfony LTS versions as a dependency for phpcpd

**Comment by sebastianbergmann** [comment]
AFAIK 2.8 is the LTS release, not 2.7.

**Comment by sergeyz** [comment]
It is, according to version checker
[Symfony 2.7 is a long term support version with 3 years support that was published in May 2015.](https://symfony.com/roadmap?version=2.7#checker)
[Symfony 2.8 is a long term support version with 3 years support that was published in November 2015.](https://symfony.com/roadmap?version=2.8#checker) and [Schedule](https://symfony.com/doc/current/contributing/community/releases.html#schedule)

**Comment by sergeyz** [comment]
Thanks, @sebastianbergmann !

**Pull request merged**
